services:
  db:
    image: postgres:15
    container_name: myfigudb_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myfigudb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: myfigudb_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@myfigudb.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./server
    container_name: myfigudb_backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - ./server/uploads:/app/uploads
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/myfigudb

volumes:
  pgdata:
